### ISSUE TITLE
references in PNAS style

### ISSUE THREAD

**Issue by tommy-engels** [jefferislab/pnaslatex#10]
In the current implementation (which is *a lot* better than the official PNAS template), the references are not set in a style similar to PNAS, which render manuscript length estimates difficult.

**Comment by ajdm** [comment]
If using BibTeX, I recommend the use of either [``pnas.bst``](https://www.ctan.org/pkg/pnas?lang=en), [``pnas2009.bst``](https://www.ctan.org/pkg/pnas2009?lang=en), or [``pnas2011.bst``](https://github.com/jburon/pnas2011.bst).

**Comment by jefferis** [comment]
@ajdm Which do you think is best? We could include it in the examples dir directly?

**Comment by ajdm** [comment]
[``pnas2011.bst``](https://github.com/jburon/pnas2011.bst) is the most up-to-date one, but does not seem to be available on CTAN, while [``pnas2009.bst``](https://www.ctan.org/pkg/pnas2009?lang=en) is. No-one seems to have written anything for [biblatex](https://www.ctan.org/pkg/biblatex?lang=en), but there is [a StackOverflow post](http://tex.stackexchange.com/questions/167650/is-there-a-more-recent-bibliography-style-file-bst-for-pnas) giving a [bibulous](http://nzhagen.github.io/bibulous/) template. [Another StackOverflow post](http://tex.stackexchange.com/questions/69267/citation-style-language-csl) details how [pandoc](http://pandoc.org/) can be used with the [appropriate Citation Style Language file](https://github.com/citation-style-language/styles/blob/cac22204fe6300c0e3a6c603673e122b09f07172/pnas.csl).

Perhaps the best idea would be to just enumerate these possibilities in the README?

**Comment by jefferis** [comment]
Have opted to note `pnas2011.bst` in the README and include it in the examples folder (thanks to @tommy-engels). See #11
