### ISSUE TITLE
"Significance" section runs off the bottom of the page.

### ISSUE THREAD

**Issue by jeffalstott** [jefferislab/pnaslatex#12]
There are several reports of an underfull \hbox at the line where I call '\significance':

```
Underfull \hbox (badness 10000) in paragraph at lines 135--135
Underfull \hbox (badness 6348) in paragraph at lines 135--135
Underfull \hbox (badness 4229) in paragraph at lines 135--135
Underfull \hbox (badness 1577) in paragraph at lines 135--135
```

This is the relevant section of the .tex file:

```
\maketitle

\significance{Technology is a complex phenomena, with many technologies relating to each other in different ways. The space of technologies and their relations to each other can be described as a network. If measured accurately, the technology relatedness network's structure can reveal properties of technologies and of human behavior.}

\begin{abstract}
...
```

**Comment by jeffalstott** [comment]
And the '\pubfoot' keeps going on underneath it, not even rendered on the page.

**Comment by jeffalstott** [comment]
It appears the problem was with my using the `fixltx2e` package, further upstream. That's unfortunate, because I was using it to mix starred and non-starred figures. Is there any fix for that?

**Comment by jefferis** [comment]
Thanks for your interest @jeffalstott. @ajdm is the best resource for this question and he's away at the moment. Why do you need starred figures?

**Comment by jeffalstott** [comment]
To make a two-column figure. Is there another mechanism I should be using?

**Comment by jefferis** [comment]
Hmm, we had both 2 col and 1 col figures in the PNAS paper [linked in the readme](http://www.pnas.org/content/111/36/E3805.abstract). They are indeed starred and non-starred, respectively. But we didn't need `fixltx2e`. I see this:

https://en.wikibooks.org/wiki/LaTeX/Floats,_Figures_and_Captions#Wide_figures_in_two_column_documents 

so is the ordering a problem if you omit `fixltx2e`? I'm no expert on this, but it looks like we used an explicit location for the single column figure:

```
\begin{figure}[t]
```

and everything behaved ok.

**Comment by jeffalstott** [comment]
It's not presently a problem for me any longer; I'm now only using one column figures. However, yes, mixing `figure*` and `figure` can create ordering problems, without `fixltx2e`.

**Comment by jefferis** [comment]
OK well @ajdm, I think you'll have to decide if this is a bug or wontfix for now.

**Comment by jdmanton** [comment]
Have you tried using `dblfloatfix` instead of `fixltx2e`? (http://www.tex.ac.uk/FAQ-2colfltorder.html) As for the issue itself, I think this is something we can't really fix, as the float ordering issue is part of LaTeX itself and the errors don't appear if `fixltx2e` isn't used.
