### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by yhtang** [jefferislab/pnaslatex#13]
Hi,
First of all thank you so much for creating a replacement to the PNAS's evil template!
However when I tried to compile with class file, I got the errors:

```
! The font "TeX Gyre Termes" cannot be found.
```

Despite that the font package is already installed on my Fedora 21.
Is there any workaround?

Best,
Yu-Hang

**Comment by jefferis** [comment]
Dear Yu-Hang, Many thanks for your positive comments. @ajdm who wrote the template is away at the moment and these font issues are not my area of speciality. Have you tried looking at tips after googling the error message:

http://tex.stackexchange.com/questions/118944/xelatex-does-not-find-texgyreterms

http://tex.stackexchange.com/questions/11888/finding-a-font-for-xetex

**Comment by yhtang** [comment]
Dear Jefferis,

I have tried some of the solutions online but they didn't work out. Could you please let me know once James is back? Thank you so much!

Yu-Hang

**Comment by jdmanton** [comment]
Hi Yu-Hang,

Where is TeX Gyre Termes currently installed?

James

**Comment by yhtang** [comment]
Hi James,

Thank you for getting back to me. I found the *gyre*.otf files at
/usr/share/texlive/texmf-dist/fonts/opentype/public/tex-gyre/

Yu-Hang

**Comment by jdmanton** [comment]
Could you please send a full listing of that directory, as well as the output of `fc-list | grep Termes`, please? Thanks.

**Comment by jdmanton** [comment]
@yhtang Did you solve this problem, in the end?
