### ISSUE TITLE
Myriad Pro issues

### ISSUE THREAD

**Issue by spmp** [jefferislab/pnaslatex#8]
On GNU/Linux with TexLive 2014
I have installed Myriad Pro via FontPro, but still get errors of Myriad Pro font not being found.
``
! fontspec error: "font-not-found"
! 
! The font "Myriad Pro" cannot be found.
``
I have tried some minimal examples to ensure that Myriad Pro is installed, and it works, but none of the \fontspec commands work.

help!! Can you put some more information in the Readme.md relating to Myriad Pro, which version or whatever and where from (and maybe how).

Cheers.

**Comment by ajdm** [comment]
``fontspec`` uses OpenType fonts, like most modern programs, rather than the METAFONT system that 'traditional' LaTeX and FontPro provides. The easiest way to obtain the OpenType fonts is to extract them from Adobe Reader or to download them from an online font repository.

**Comment by ajdm** [comment]
If you wish to use a different OpenType font, just changes lines 15–18 in the ``pnas.cls`` file.

**Comment by spmp** [comment]
The fonts from Adobe Reader 9 do not have the semibold style. I managed to get the ful set from Font Folio 11.
Thanks for the very quick response!
But for fools like myself can yo please make a note of it in the Readme.
I would like the options to use the Koma default fonts for now, what fonts would we replace these with?

**Comment by ajdm** [comment]
> The fonts from Adobe Reader 9 do not have the semibold style. I managed to get the ful set from Font Folio 11.

Ah, that's interesting. I'll investigate that and remove the semibold style in the future. Thanks.

> But for fools like myself can yo please make a note of it in the Readme.

Will do.

> I would like the options to use the Koma default fonts for now, what fonts would we replace these with?

Unless I've misunderstood your question, the KOMA* document classes don't set a default font, and so this should just be Computer Modern.

**Comment by jeffalstott** [comment]
I know nothing about fonts. I tried for several hours to figure out how to make this work, to no avail. Tried just replacing all instances in the .cls file of "Myriad Pro" to "Computer Modern Sans". That also didn't work. Can this be made to work with non-proprietary fonts? Otherwise I can't even get off the ground.

**Comment by jdmanton** [comment]
@jeffalstott Sorry for the delayed response, I seem to have missed the notification of your post. Changing the fonts to 'Computer Modern Sans' will only work if you have the OpenType/TrueType versions installed on your computer (it won't use the METAFONT versions that LaTeX normally uses). If you don't have these installed, you can either download them from http://www.gust.org.pl/projects/e-foundry/latin-modern or use some other font that is installed on your system, such as 'Arial' or 'Helvetica'.
