### ISSUE TITLE
add LyX template file

### ISSUE THREAD

**Issue by tommy-engels** [jefferislab/pnaslatex#9]
It would be really great for new users if you could provide a LyX template file. 
For instance, I struggled with the switch 
Documents-Settings-Fonts-"use non-tex fonts.."
which has to be activated.

**Comment by jefferis** [comment]
Thanks for the interest and suggestion. @ajdm I'll try and make a cut down version of our paper.

**Comment by tommy-engels** [comment]
I really appreciate your community efforts. PNAS is a nightmare, I also struggled quite some time with the official files, without success.

**Comment by ajdm** [comment]
@jefferis Thanks. @tommy-engels Would a blank template, with all environments filled with short placeholders and document settings set also be useful?

**Comment by jefferis** [comment]
Hi @ajdm, so I tried making a minimal version of our LyX ms:

https://github.com/jefferislab/pnaslatex/compare/lyx-template?expand=1

but I am getting compile errors that a brief inspection couldn't resolve. Any ideas?

**Comment by tommy-engels** [comment]
any example would be fine and useful. it would however be good (my opinion) if it included stuff like affiliations, author footnotes, materials and methods and so on. and references :)

**Comment by ajdm** [comment]
@jefferis It looks like (for reasons I don't understand), LyX is not adding the ``refstyle`` package to the LaTeX it outputs, which is necessary for the ``\newref`` commands in the preamble (despite the requisite checkbox being ticked in the document settings). Adding an explicit ``\usepackage{refstyle}`` to the preamble allows me to compile the LyX file.

**Comment by tommy-engels** [comment]
actually, the example is already quite helpful to me, even though it does not compile.
On my system (fedora with texlive-full), the sidecap package is missing (and I cannot install it from official repos)

I learned the \sloppy command from it

for me, it is the same with the refstyle package

**Comment by ajdm** [comment]
@tommy-engels Would the standard PNAS example, recreated using this document class with [this LaTeX code](https://github.com/jefferislab/pnaslatex/blob/master/examples/pnas_example.tex) to produce [this output](https://github.com/jefferislab/pnaslatex/blob/master/examples/pnas_example.pdf), but done using the LyX template be useful?

**Comment by tommy-engels** [comment]
that would be the best , I think

**Comment by ajdm** [comment]
Both [``refstyle``](https://www.ctan.org/pkg/refstyle?lang=en) and [``sidecap``](https://www.ctan.org/pkg/sidecap) are available from CTAN.

**Comment by tommy-engels** [comment]
I also prepared an example, maybe I can send it to you by email ? if you like of course.

**Comment by ajdm** [comment]
@tommy-engels That would be useful, thanks. The more examples the better!

**Comment by jefferis** [comment]
closed by merging #11
